# %% [markdown]
# # EXP01: CatBoost IPCW Pair-Rank Diagnostics
#
# Diagnostics-only CatBoost pairwise ranking experiment for censored survival.
# The first pass uses V6 dense features only, GroupKFold by CENTER only, and
# fold-local preprocessing. No submission files are generated by this script.

# %%
try:
    import sksurv  # noqa: F401
except Exception:
    try:
        import google.colab  # noqa: F401
        get_ipython().system("pip -q install scikit-survival")
    except Exception as exc:
        raise ImportError(
            "scikit-survival is required. In Colab, run: !pip -q install scikit-survival"
        ) from exc

import gc
import os
import re
import sys
import time
import zipfile
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler

from sksurv.metrics import concordance_index_ipcw
from sksurv.util import Surv

try:
    from catboost import CatBoostRanker, Pool

    HAS_CATBOOST = True
    CATBOOST_IMPORT_ERROR = ""
except Exception as exc:
    CatBoostRanker = None
    Pool = None
    HAS_CATBOOST = False
    CATBOOST_IMPORT_ERROR = repr(exc)

RANDOM_STATE = 42
TAU = 7.0
MAX_COMPARATORS_PER_ANCHOR = 32


def env_flag(name, default=True):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() not in {"0", "false", "no", "off"}


RUN_RANDOM_KFOLD_DIAGNOSTIC = env_flag("RUN_RANDOM_KFOLD_DIAGNOSTIC", False)
RUN_LOCO_DIAGNOSTIC = env_flag("RUN_LOCO_DIAGNOSTIC", False)
EXP01_QUICK_CHECK_ONLY = env_flag("EXP01_QUICK_CHECK_ONLY", False)
SAVE_EXP01_SUBMISSIONS = env_flag("SAVE_EXP01_SUBMISSIONS", False)

assert not RUN_RANDOM_KFOLD_DIAGNOSTIC, "Random KFold is disabled for EXP01."
assert not RUN_LOCO_DIAGNOSTIC, "LOCO diagnostics are disabled for EXP01."
assert not SAVE_EXP01_SUBMISSIONS, "EXP01 is diagnostics-only; submissions are disabled."

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 180)
np.random.seed(RANDOM_STATE)

try:
    display  # type: ignore[name-defined]
except NameError:

    def display(obj):
        if hasattr(obj, "to_string"):
            print(obj.to_string())
        else:
            print(obj)


# %% [markdown]
# # Paths and raw data

# %%
def first_existing_dir(candidates):
    for path in candidates:
        if path.exists():
            return path
    return candidates[0]


DATA_DIR = first_existing_dir(
    [
        Path("/content/QRT_blood"),
        Path("/content"),
        Path(r"C:\Users\maze2\Downloads\QRT_blood"),
    ]
)

OUTPUT_DIR = first_existing_dir([Path("/content"), Path.cwd()]) / "qrt_outputs_exp01"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_ZIP = DATA_DIR / "X_train_9po2I7U.zip"
TEST_ZIP = DATA_DIR / "X_test_xzVefmA.zip"
TARGET_PATH = DATA_DIR / "target_train.csv"
RANDOM_SUB_PATH = DATA_DIR / "random_submission_FRacdcw_v9kP4pP.csv"

print("DATA_DIR:", DATA_DIR)
print("OUTPUT_DIR:", OUTPUT_DIR)
for required in [TRAIN_ZIP, TEST_ZIP, TARGET_PATH, RANDOM_SUB_PATH]:
    print(required.name, "exists:", required.exists())


def read_csv_from_zip(zip_path, inner_path):
    with zipfile.ZipFile(zip_path) as zf:
        with zf.open(inner_path) as fh:
            return pd.read_csv(fh)


clinical_train = read_csv_from_zip(TRAIN_ZIP, "X_train/clinical_train.csv")
molecular_train = read_csv_from_zip(TRAIN_ZIP, "X_train/molecular_train.csv")
clinical_test = read_csv_from_zip(TEST_ZIP, "X_test/clinical_test.csv")
molecular_test = read_csv_from_zip(TEST_ZIP, "X_test/molecular_test.csv")
target = pd.read_csv(TARGET_PATH)
random_submission = pd.read_csv(RANDOM_SUB_PATH)

for df in [clinical_train, molecular_train, clinical_test, molecular_test, target, random_submission]:
    if "ID" in df.columns:
        df["ID"] = df["ID"].astype(str)

assert set(clinical_train["ID"]) == set(target["ID"]), "Train clinical IDs and target IDs differ."
assert list(clinical_train["ID"]) == list(target["ID"]), "Train clinical and target row order differ."
assert set(clinical_test["ID"]) == set(random_submission["ID"]), "Test clinical IDs and random submission IDs differ."
assert list(clinical_test["ID"]) == list(random_submission["ID"]), "Test clinical and random submission row order differ."
assert set(molecular_train["ID"]).issubset(set(clinical_train["ID"])), "Train molecular has IDs not in clinical."
assert set(molecular_test["ID"]).issubset(set(clinical_test["ID"])), "Test molecular has IDs not in clinical."

print("clinical_train:", clinical_train.shape)
print("molecular_train:", molecular_train.shape)
print("target:", target.shape)
print("clinical_test:", clinical_test.shape)
print("molecular_test:", molecular_test.shape)
print("random_submission:", random_submission.shape)


# %% [markdown]
# # Full survival target

# %%
target_clean = target.dropna(subset=["OS_YEARS", "OS_STATUS"]).copy()
target_clean["ID"] = target_clean["ID"].astype(str)
target_clean["event_full"] = target_clean["OS_STATUS"].astype(bool)
target_clean["time_full"] = target_clean["OS_YEARS"].astype(float)

train_ids = target_clean["ID"].tolist()
test_ids = random_submission["ID"].tolist()
groups_center = clinical_train.set_index("ID").loc[train_ids, "CENTER"].values

y_full = Surv.from_arrays(
    event=target_clean["event_full"].to_numpy(dtype=bool),
    time=target_clean["time_full"].to_numpy(dtype=float),
)
y = y_full

print("Clean training rows:", len(train_ids))
print("Full target event rate:", round(float(target_clean["event_full"].mean()), 4))
print("Max full time:", target_clean["time_full"].max())


def y_event_time(y_arr):
    names = y_arr.dtype.names
    if names is None or len(names) < 2:
        raise ValueError("Expected a structured survival array.")
    return y_arr[names[0]].astype(bool), y_arr[names[1]].astype(float)


# %% [markdown]
# # V6 dense feature builder
#
# These are the same V6 feature families used by the current best dense-model
# diagnostics. `CENTER` and raw `CYTOGENETICS` are never model features.

# %%
NUMERIC_CLINICAL_COLS = ["BM_BLAST", "WBC", "ANC", "MONOCYTES", "HB", "PLT"]


def safe_numeric(series):
    return pd.to_numeric(series, errors="coerce")


def safe_divide(num, den):
    out = num / den.replace(0, np.nan)
    return out.replace([np.inf, -np.inf], np.nan)


def make_clinical_features(df):
    f = pd.DataFrame(index=df["ID"].astype(str))
    raw = {}
    for col in NUMERIC_CLINICAL_COLS:
        raw[col] = safe_numeric(df[col])
        f[col] = raw[col].to_numpy()
        f[f"{col}_missing"] = raw[col].isna().astype(float).to_numpy()
        f[f"log1p_{col}"] = np.log1p(raw[col].clip(lower=0)).to_numpy()

    f["ANC_WBC_ratio"] = safe_divide(raw["ANC"], raw["WBC"]).to_numpy()
    f["MONOCYTES_WBC_ratio"] = safe_divide(raw["MONOCYTES"], raw["WBC"]).to_numpy()
    f["PLT_HB_ratio"] = safe_divide(raw["PLT"], raw["HB"]).to_numpy()
    f["WBC_PLT_ratio"] = safe_divide(raw["WBC"], raw["PLT"]).to_numpy()
    f["blast_x_wbc"] = (raw["BM_BLAST"] * raw["WBC"]).to_numpy()
    f["blast_x_logwbc"] = (raw["BM_BLAST"] * np.log1p(raw["WBC"].clip(lower=0))).to_numpy()
    f["anemia_thrombocytopenia"] = ((raw["HB"] < 10) & (raw["PLT"] < 100)).astype(float).to_numpy()
    f["severe_cytopenia_count"] = (
        (raw["HB"] < 8).astype(float)
        + (raw["PLT"] < 50).astype(float)
        + (raw["ANC"] < 0.5).astype(float)
    ).to_numpy()

    thresholds = {
        "BM_BLAST": [2, 5, 10, 20, 30],
        "WBC": [1, 3, 10, 20, 50],
        "ANC": [0.5, 1.0, 1.5],
        "MONOCYTES": [0.2, 0.5, 1.0],
        "HB": [8, 10, 12],
        "PLT": [20, 50, 100, 150],
    }
    for col, vals in thresholds.items():
        for val in vals:
            op = "lt" if col in ["ANC", "HB", "PLT"] else "ge"
            safe_val = str(val).replace(".", "p")
            if op == "lt":
                f[f"{col}_{op}_{safe_val}"] = (raw[col] < val).astype(float).to_numpy()
            else:
                f[f"{col}_{op}_{safe_val}"] = (raw[col] >= val).astype(float).to_numpy()

    assert "CENTER" not in f.columns
    return f


CYTO_PATTERNS = {
    "cyto_del5q": r"del\(5\)|5q-|del\(5q\)",
    "cyto_monosomy5": r"(?<!\d)-5(?!\d)",
    "cyto_del7q": r"del\(7\)|7q-|del\(7q\)",
    "cyto_monosomy7": r"(?<!\d)-7(?!\d)",
    "cyto_plus8": r"(?<!\d)\+8(?!\d)",
    "cyto_del11q": r"del\(11\)|11q-|del\(11q\)",
    "cyto_del12p": r"del\(12\)|12p-|del\(12p\)",
    "cyto_del13q": r"del\(13\)|13q-|del\(13q\)",
    "cyto_del17p": r"del\(17\)|17p-|del\(17p\)|i\(17q\)",
    "cyto_del20q": r"del\(20\)|20q-|del\(20q\)",
    "cyto_inv3_or_t3q": r"inv\(3\)|t\(3;3\)|3q26|q26\.2",
    "cyto_t_8_21": r"t\(8;21\)",
    "cyto_inv16": r"inv\(16\)|t\(16;16\)",
    "cyto_t_15_17": r"t\(15;17\)",
    "cyto_kmt2a_11q23": r"11q23|q23",
    "cyto_marker_or_ring": r"mar|r\(",
    "cyto_derivative": r"der\(",
    "cyto_dicentric": r"dic\(",
    "cyto_additional": r"add\(",
    "cyto_translocation": r"t\(",
    "cyto_inversion": r"inv\(",
}


def normalize_cyto_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip().lower().replace(" ", "")


def make_cytogenetic_features(df):
    texts = df["CYTOGENETICS"].map(normalize_cyto_text)
    f = pd.DataFrame(index=df["ID"].astype(str))
    f["cyto_missing"] = (texts == "").astype(float).to_numpy()
    f["cyto_text_len"] = texts.str.len().astype(float).to_numpy()
    f["cyto_clone_count"] = texts.str.count("/").add(1).where(texts != "", 0).astype(float).to_numpy()
    f["cyto_uncertain_count"] = texts.str.count(r"\?").astype(float).to_numpy()
    f["cyto_has_uncertainty"] = (f["cyto_uncertain_count"] > 0).astype(float)
    f["cyto_normal_word"] = texts.str.contains("normal", regex=False).astype(float).to_numpy()
    f["cyto_plain_46xx_or_46xy"] = texts.isin(["46,xx", "46,xy"]).astype(float).to_numpy()

    event_regex = r"del\(|add\(|der\(|dic\(|inv\(|ins\(|t\(|mar|r\(|(?<!\d)[+-](?:[1-9]|1[0-9]|2[0-2]|x|y)(?!\d)"
    f["cyto_event_count_est"] = texts.str.count(event_regex).astype(float).to_numpy()
    f["cyto_abnormal"] = ((f["cyto_event_count_est"] > 0) | (f["cyto_normal_word"] == 0)).astype(float)

    for name, pattern in CYTO_PATTERNS.items():
        f[name] = texts.str.contains(pattern, regex=True).astype(float).to_numpy()

    f["cyto_minus7_or_del7q"] = ((f["cyto_monosomy7"] > 0) | (f["cyto_del7q"] > 0)).astype(float)
    f["cyto_minus5_or_del5q"] = ((f["cyto_monosomy5"] > 0) | (f["cyto_del5q"] > 0)).astype(float)
    f["cyto_complex_3plus"] = (f["cyto_event_count_est"] >= 3).astype(float)
    f["cyto_complex_5plus"] = (f["cyto_event_count_est"] >= 5).astype(float)

    adverse_cols = [
        "cyto_minus7_or_del7q",
        "cyto_minus5_or_del5q",
        "cyto_del17p",
        "cyto_inv3_or_t3q",
        "cyto_kmt2a_11q23",
        "cyto_complex_3plus",
    ]
    favorable_cols = ["cyto_t_8_21", "cyto_inv16", "cyto_t_15_17"]
    f["cyto_adverse_score"] = f[adverse_cols].sum(axis=1)
    f["cyto_favorable_score"] = f[favorable_cols].sum(axis=1)
    f["cyto_intermediate_like"] = ((f["cyto_adverse_score"] == 0) & (f["cyto_favorable_score"] == 0)).astype(float)

    for chrom in [str(i) for i in range(1, 23)] + ["x", "y"]:
        f[f"cyto_chr_{chrom}_mentioned"] = texts.str.contains(
            rf"(?<!\d){chrom}(?!\d)|\({chrom}[;,\)]|;{chrom}[;,\)]", regex=True
        ).astype(float).to_numpy()

    return f


KEY_GENES = [
    "TP53",
    "NPM1",
    "FLT3",
    "DNMT3A",
    "TET2",
    "ASXL1",
    "RUNX1",
    "SRSF2",
    "SF3B1",
    "U2AF1",
    "EZH2",
    "IDH1",
    "IDH2",
    "NRAS",
    "KRAS",
    "CBL",
    "JAK2",
    "BCOR",
    "STAG2",
    "WT1",
    "CEBPA",
    "DDX41",
    "ZRSR2",
    "ETV6",
    "GATA2",
    "KIT",
]

GENE_SETS = {
    "signaling": ["FLT3", "NRAS", "KRAS", "CBL", "JAK2", "KIT", "PTPN11"],
    "methylation": ["DNMT3A", "TET2", "IDH1", "IDH2"],
    "spliceosome": ["SRSF2", "SF3B1", "U2AF1", "ZRSR2"],
    "chromatin": ["ASXL1", "EZH2", "BCOR", "STAG2", "KMT2A"],
    "transcription": ["RUNX1", "CEBPA", "GATA2", "ETV6", "WT1"],
    "tumor_suppressor": ["TP53", "DDX41", "PHF6"],
}

TOP_N_GENES = 80
TOP_N_EFFECTS = 12

train_gene_counts = molecular_train["GENE"].fillna("UNKNOWN").astype(str).value_counts()
train_effect_counts = molecular_train["EFFECT"].fillna("UNKNOWN").astype(str).value_counts()
SELECTED_GENES = list(dict.fromkeys(train_gene_counts.head(TOP_N_GENES).index.tolist() + KEY_GENES))
SELECTED_EFFECTS = list(dict.fromkeys(train_effect_counts.head(TOP_N_EFFECTS).index.tolist()))


def make_molecular_features(mol, patient_ids, selected_genes, selected_effects):
    patient_ids = pd.Index(pd.Series(patient_ids).astype(str), name="ID")
    m = mol.copy()
    m["ID"] = m["ID"].astype(str)
    m["GENE"] = m["GENE"].fillna("UNKNOWN").astype(str)
    m["EFFECT"] = m["EFFECT"].fillna("UNKNOWN").astype(str)
    m["VAF"] = pd.to_numeric(m["VAF"], errors="coerce")
    m["DEPTH"] = pd.to_numeric(m["DEPTH"], errors="coerce")
    m["REF"] = m["REF"].fillna("").astype(str)
    m["ALT"] = m["ALT"].fillna("").astype(str)
    m = m[m["ID"].isin(patient_ids)]

    f = pd.DataFrame(index=patient_ids)
    count = m.groupby("ID").size()
    f["Nmut"] = count.reindex(patient_ids, fill_value=0).astype(float)
    f["has_any_mutation"] = (f["Nmut"] > 0).astype(float)

    for col in ["VAF", "DEPTH"]:
        grp = m.groupby("ID")[col]
        f[f"{col}_mean"] = grp.mean().reindex(patient_ids)
        f[f"{col}_median"] = grp.median().reindex(patient_ids)
        f[f"{col}_max"] = grp.max().reindex(patient_ids)
        f[f"{col}_min"] = grp.min().reindex(patient_ids)
        f[f"{col}_std"] = grp.std().reindex(patient_ids)

    f["VAF_gt_0p10_count"] = m.assign(flag=(m["VAF"] > 0.10).astype(float)).groupby("ID")["flag"].sum().reindex(patient_ids, fill_value=0)
    f["VAF_gt_0p25_count"] = m.assign(flag=(m["VAF"] > 0.25).astype(float)).groupby("ID")["flag"].sum().reindex(patient_ids, fill_value=0)
    f["VAF_gt_0p40_count"] = m.assign(flag=(m["VAF"] > 0.40).astype(float)).groupby("ID")["flag"].sum().reindex(patient_ids, fill_value=0)
    f["VAF_lt_0p05_count"] = m.assign(flag=(m["VAF"] < 0.05).astype(float)).groupby("ID")["flag"].sum().reindex(patient_ids, fill_value=0)

    m["is_snv"] = ((m["REF"].str.len() == 1) & (m["ALT"].str.len() == 1)).astype(float)
    m["is_indel"] = (m["REF"].str.len() != m["ALT"].str.len()).astype(float)
    f["snv_count"] = m.groupby("ID")["is_snv"].sum().reindex(patient_ids, fill_value=0)
    f["indel_count"] = m.groupby("ID")["is_indel"].sum().reindex(patient_ids, fill_value=0)
    f["indel_fraction"] = f["indel_count"] / f["Nmut"].replace(0, np.nan)

    effect_counts = (
        m[m["EFFECT"].isin(selected_effects)]
        .pivot_table(index="ID", columns="EFFECT", values="GENE", aggfunc="size", fill_value=0)
        .reindex(index=patient_ids, columns=selected_effects, fill_value=0)
    )
    for effect in selected_effects:
        clean = re.sub(r"[^0-9a-zA-Z]+", "_", effect).strip("_")
        f[f"effect_count_{clean}"] = effect_counts[effect].astype(float)

    for gene in selected_genes:
        sub = m[m["GENE"] == gene]
        safe_gene = re.sub(r"[^0-9a-zA-Z]+", "_", gene).strip("_")
        gene_count = sub.groupby("ID").size().reindex(patient_ids, fill_value=0).astype(float)
        f[f"gene_{safe_gene}_count"] = gene_count
        f[f"gene_{safe_gene}_flag"] = (gene_count > 0).astype(float)
        f[f"gene_{safe_gene}_max_vaf"] = sub.groupby("ID")["VAF"].max().reindex(patient_ids)

    for set_name, genes in GENE_SETS.items():
        sub = m[m["GENE"].isin(genes)]
        set_count = sub.groupby("ID").size().reindex(patient_ids, fill_value=0).astype(float)
        f[f"pathway_{set_name}_count"] = set_count
        f[f"pathway_{set_name}_flag"] = (set_count > 0).astype(float)
        f[f"pathway_{set_name}_max_vaf"] = sub.groupby("ID")["VAF"].max().reindex(patient_ids)

    return f.replace([np.inf, -np.inf], np.nan)


def assemble_features(clinical_features, cyto_features, molecular_features):
    f = pd.concat([clinical_features, cyto_features, molecular_features], axis=1)

    def get_col(name, default=0.0):
        if name in f.columns:
            return f[name].fillna(0)
        return pd.Series(default, index=f.index)

    f["interaction_TP53_complex"] = get_col("gene_TP53_flag") * get_col("cyto_complex_3plus")
    f["interaction_TP53_del17p"] = get_col("gene_TP53_flag") * get_col("cyto_del17p")
    f["interaction_NPM1_FLT3"] = get_col("gene_NPM1_flag") * get_col("gene_FLT3_flag")
    f["interaction_ASXL1_RUNX1"] = get_col("gene_ASXL1_flag") * get_col("gene_RUNX1_flag")
    f["interaction_spliceosome_anemia"] = get_col("pathway_spliceosome_flag") * get_col("HB_lt_10")
    f["interaction_signaling_high_wbc"] = get_col("pathway_signaling_flag") * get_col("WBC_ge_10")
    f["interaction_methylation_high_nmut"] = get_col("pathway_methylation_flag") * (get_col("Nmut") >= 4).astype(float)

    f = f.apply(pd.to_numeric, errors="coerce")
    return f.replace([np.inf, -np.inf], np.nan)


def clean_numeric_feature_frame(f, label):
    f = f.apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)
    if f.columns.duplicated().any():
        duplicates = f.columns[f.columns.duplicated()].tolist()
        raise ValueError(f"Duplicate raw feature names in {label}: {duplicates[:10]}")
    return f


clinical_features_train = make_clinical_features(clinical_train)
clinical_features_test = make_clinical_features(clinical_test)
cyto_features_train = make_cytogenetic_features(clinical_train)
cyto_features_test = make_cytogenetic_features(clinical_test)
molecular_features_train = make_molecular_features(molecular_train, clinical_train["ID"], SELECTED_GENES, SELECTED_EFFECTS)
molecular_features_test = make_molecular_features(molecular_test, clinical_test["ID"], SELECTED_GENES, SELECTED_EFFECTS)

feature_train_v6 = assemble_features(clinical_features_train, cyto_features_train, molecular_features_train)
feature_test_v6 = assemble_features(clinical_features_test, cyto_features_test, molecular_features_test)

X_train_raw = clean_numeric_feature_frame(feature_train_v6.copy(), "exp01/v6/train").loc[train_ids].copy()
X_test_raw = clean_numeric_feature_frame(feature_test_v6.copy(), "exp01/v6/test").reindex(columns=X_train_raw.columns).loc[test_ids].copy()

assert "CENTER" not in X_train_raw.columns and "CENTER" not in X_test_raw.columns
assert "CYTOGENETICS" not in X_train_raw.columns and "CYTOGENETICS" not in X_test_raw.columns
assert list(X_train_raw.columns) == list(X_test_raw.columns)
assert list(X_test_raw.index) == list(random_submission["ID"])
assert not X_train_raw.columns.duplicated().any()
assert not X_test_raw.columns.duplicated().any()

feature_counts = pd.DataFrame(
    [
        {
            "feature_set": "v6_dense_only",
            "train_rows": X_train_raw.shape[0],
            "train_features": X_train_raw.shape[1],
            "test_rows": X_test_raw.shape[0],
            "test_features": X_test_raw.shape[1],
            "center_absent": "CENTER" not in X_train_raw.columns and "CENTER" not in X_test_raw.columns,
            "cytogenetics_absent": "CYTOGENETICS" not in X_train_raw.columns and "CYTOGENETICS" not in X_test_raw.columns,
            "train_test_columns_match": list(X_train_raw.columns) == list(X_test_raw.columns),
        }
    ]
)
feature_counts.to_csv(OUTPUT_DIR / "exp01_feature_counts.csv", index=False)
display(feature_counts)

print("EXP01 V6-only train shape:", X_train_raw.shape)
print("EXP01 V6-only test shape:", X_test_raw.shape)
print("CENTER absent:", "CENTER" not in X_train_raw.columns and "CENTER" not in X_test_raw.columns)
print("CYTOGENETICS absent:", "CYTOGENETICS" not in X_train_raw.columns and "CYTOGENETICS" not in X_test_raw.columns)
print("train/test columns match:", list(X_train_raw.columns) == list(X_test_raw.columns))


# %% [markdown]
# # Candidate manifest and dependency/preflight checks

# %%
EXP01_CATBOOST_CONFIGS = [
    {
        "name": "cb_pairlogit_d4_lr03_it300",
        "family": "catboost_pairrank",
        "loss_function": "PairLogitPairwise",
        "depth": 4,
        "learning_rate": 0.03,
        "iterations": 300,
        "l2_leaf_reg": 10.0,
    },
    {
        "name": "cb_pairlogit_d6_lr02_it400",
        "family": "catboost_pairrank",
        "loss_function": "PairLogitPairwise",
        "depth": 6,
        "learning_rate": 0.02,
        "iterations": 400,
        "l2_leaf_reg": 10.0,
    },
    {
        "name": "cb_pairlogit_d4_lr02_it600",
        "family": "catboost_pairrank",
        "loss_function": "PairLogitPairwise",
        "depth": 4,
        "learning_rate": 0.02,
        "iterations": 600,
        "l2_leaf_reg": 20.0,
    },
    {
        "name": "cb_yetirank_d4_lr03_it300",
        "family": "catboost_pairrank",
        "loss_function": "YetiRankPairwise",
        "depth": 4,
        "learning_rate": 0.03,
        "iterations": 300,
        "l2_leaf_reg": 10.0,
    },
]

candidate_manifest = pd.DataFrame(EXP01_CATBOOST_CONFIGS)
candidate_manifest.to_csv(OUTPUT_DIR / "exp01_candidate_manifest.csv", index=False)

dependency_status = pd.DataFrame(
    [
        {
            "family": "catboost",
            "available": bool(HAS_CATBOOST),
            "status": "available" if HAS_CATBOOST else "missing",
            "message": (
                "available"
                if HAS_CATBOOST
                else (
                    "CatBoost unavailable; skipping EXP01 CatBoost CV. "
                    "Install separately with: .\\.venv\\Scripts\\python.exe -m pip install catboost. "
                    f"Import error: {CATBOOST_IMPORT_ERROR}"
                )
            ),
        }
    ]
)
dependency_status.to_csv(OUTPUT_DIR / "exp01_dependency_status.csv", index=False)
display(dependency_status)


def run_catboost_preflight():
    if not HAS_CATBOOST:
        return pd.DataFrame(
            [
                {
                    "loss_function": "PairLogitPairwise",
                    "status": "skipped_missing_dependency",
                    "message": "CatBoost missing; install with .\\.venv\\Scripts\\python.exe -m pip install catboost",
                },
                {
                    "loss_function": "YetiRankPairwise",
                    "status": "skipped_missing_dependency",
                    "message": "CatBoost missing; install with .\\.venv\\Scripts\\python.exe -m pip install catboost",
                },
            ]
        )

    rows = []
    X_tiny = np.array(
        [
            [2.0, 0.0],
            [0.0, 1.0],
            [0.1, 0.2],
            [1.5, 0.5],
            [0.4, 0.1],
            [0.2, 0.3],
        ],
        dtype=np.float32,
    )
    y_tiny = np.array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0], dtype=np.float32)
    group_id = np.array([0, 0, 0, 1, 1, 1], dtype=np.int64)
    pairs = np.array([[0, 1], [0, 2], [3, 4], [3, 5]], dtype=np.int32)
    pairs_weight = np.ones(len(pairs), dtype=np.float32)

    for loss_function in ["PairLogitPairwise", "YetiRankPairwise"]:
        try:
            pool = Pool(
                data=X_tiny,
                label=y_tiny,
                group_id=group_id,
                pairs=pairs,
                pairs_weight=pairs_weight,
            )
            model = CatBoostRanker(
                loss_function=loss_function,
                iterations=2,
                depth=1,
                learning_rate=0.1,
                random_seed=RANDOM_STATE,
                thread_count=1,
                allow_writing_files=False,
                verbose=False,
                task_type="CPU",
            )
            model.fit(pool)
            pred = np.asarray(model.predict(X_tiny), dtype=float)
            if pred.shape[0] != X_tiny.shape[0] or not np.isfinite(pred).all():
                raise ValueError("non-finite or wrong-length preflight predictions")
            rows.append(
                {
                    "loss_function": loss_function,
                    "status": "passed",
                    "message": "tiny pairwise preflight produced finite predictions",
                }
            )
        except Exception as exc:
            rows.append(
                {
                    "loss_function": loss_function,
                    "status": "failed",
                    "message": repr(exc),
                }
            )
    return pd.DataFrame(rows)


catboost_preflight_status = run_catboost_preflight()
catboost_preflight_status.to_csv(OUTPUT_DIR / "exp01_catboost_preflight_status.csv", index=False)
display(catboost_preflight_status)
CATBOOST_PREFLIGHT_PASSED = bool(
    HAS_CATBOOST and (catboost_preflight_status["status"] == "passed").all()
)


# %% [markdown]
# # Fold-local preprocessing and pair-query construction

# %%
class FoldPreprocessor:
    def fit(self, X):
        assert "CENTER" not in X.columns
        assert "CYTOGENETICS" not in X.columns
        self.input_columns_ = X.columns.tolist()

        self.kept_not_all_missing_ = X.columns[~X.isna().all(axis=0)].tolist()
        if len(self.kept_not_all_missing_) == 0:
            raise ValueError("All columns are all-missing in this training fold.")

        X0 = X[self.kept_not_all_missing_].copy()
        self.imputer_ = SimpleImputer(strategy="median")
        Xi = pd.DataFrame(
            self.imputer_.fit_transform(X0),
            columns=self.kept_not_all_missing_,
            index=X.index,
        )

        self.kept_nonconstant_ = Xi.columns[Xi.nunique(dropna=False) > 1].tolist()
        if len(self.kept_nonconstant_) == 0:
            raise ValueError("No nonconstant columns remain after fold-local imputation.")
        Xi = Xi[self.kept_nonconstant_]

        self.kept_columns_ = Xi.T.drop_duplicates().T.columns.tolist()
        if len(self.kept_columns_) == 0:
            raise ValueError("No columns remain after fold-local duplicate removal.")

        self.scaler_ = StandardScaler()
        self.scaler_.fit(Xi[self.kept_columns_])
        return self

    def transform(self, X):
        assert "CENTER" not in X.columns
        assert "CYTOGENETICS" not in X.columns
        X0 = X[self.kept_not_all_missing_].copy()
        Xi = pd.DataFrame(
            self.imputer_.transform(X0),
            columns=self.kept_not_all_missing_,
            index=X.index,
        )
        Xi = Xi[self.kept_columns_]
        Xi = pd.DataFrame(
            self.scaler_.transform(Xi),
            columns=self.kept_columns_,
            index=X.index,
        )
        assert np.isfinite(Xi.to_numpy()).all()
        return Xi


def rank01(values):
    values = np.asarray(values, dtype=float)
    return pd.Series(values).rank(method="average").to_numpy(dtype=float) / (len(values) + 1.0)


def ipcw_score(y_train_fold, y_valid_fold, pred_valid, tau=TAU):
    return float(concordance_index_ipcw(y_train_fold, y_valid_fold, pred_valid, tau=tau)[0])


def fit_censoring_km(y_train_fold):
    event, time_arr = y_event_time(y_train_fold)
    censor_event = ~event
    unique_times = np.sort(np.unique(time_arr[np.isfinite(time_arr)]))
    surv_values = []
    surv = 1.0
    for t in unique_times:
        at_risk = np.sum(time_arr >= t)
        d_censor = np.sum((time_arr == t) & censor_event)
        if at_risk > 0:
            surv *= max(0.0, 1.0 - d_censor / at_risk)
        surv_values.append(surv)
    return unique_times, np.asarray(surv_values, dtype=float)


def predict_censoring_survival(km_times, km_surv, query_times):
    query_times = np.asarray(query_times, dtype=float)
    if len(km_times) == 0:
        return np.ones_like(query_times, dtype=float)
    idx = np.searchsorted(km_times, query_times, side="right") - 1
    out = np.ones_like(query_times, dtype=float)
    valid = idx >= 0
    out[valid] = km_surv[idx[valid]]
    return out


def build_pairwise_query_data(
    X_train_pp,
    y_train_fold,
    fold_seed,
    max_comparators=MAX_COMPARATORS_PER_ANCHOR,
    materialize=True,
):
    event, time_arr = y_event_time(y_train_fold)
    anchor_idx = np.flatnonzero(event & (time_arr <= TAU))
    km_times, km_surv = fit_censoring_km(y_train_fold)

    X_np = np.asarray(X_train_pp, dtype=np.float32)
    rows = []
    labels = []
    group_ids = []
    pairs = []
    pairs_weight = []
    anchor_count = 0
    skipped_no_comparator = 0
    comparator_total_before_cap = 0
    comparator_total_after_cap = 0

    for anchor_local_idx in anchor_idx:
        anchor_time = float(time_arr[anchor_local_idx])
        comparator_idx = np.flatnonzero(time_arr > anchor_time)
        if len(comparator_idx) == 0:
            skipped_no_comparator += 1
            continue

        comparator_total_before_cap += int(len(comparator_idx))
        if len(comparator_idx) > max_comparators:
            rng = np.random.default_rng(RANDOM_STATE + fold_seed * 100000 + int(anchor_local_idx))
            comparator_idx = np.sort(rng.choice(comparator_idx, size=max_comparators, replace=False))
        comparator_total_after_cap += int(len(comparator_idx))

        ghat = float(predict_censoring_survival(km_times, km_surv, [anchor_time])[0])
        anchor_weight = min(1.0 / (max(ghat, 0.05) ** 2), 25.0)
        per_pair_weight = anchor_weight / max(len(comparator_idx), 1)

        if materialize:
            group_id = anchor_count
            anchor_row_pos = len(rows)
            rows.append(X_np[anchor_local_idx])
            labels.append(1.0)
            group_ids.append(group_id)

            for comp_local_idx in comparator_idx:
                comp_row_pos = len(rows)
                rows.append(X_np[comp_local_idx])
                labels.append(0.0)
                group_ids.append(group_id)
                pairs.append([anchor_row_pos, comp_row_pos])
                pairs_weight.append(per_pair_weight)

        anchor_count += 1

    stats = {
        "anchors_total": int(len(anchor_idx)),
        "queries_built": int(anchor_count),
        "anchors_skipped_no_comparator": int(skipped_no_comparator),
        "pairs_before_cap": int(comparator_total_before_cap),
        "pairs_after_cap": int(comparator_total_after_cap),
        "max_comparators_per_anchor": int(max_comparators),
        "materialized_rows": int(len(rows)) if materialize else 0,
    }

    if not materialize:
        return None, None, None, None, None, stats
    if len(pairs) == 0:
        raise ValueError("No comparable pairs were built from this training fold.")

    return (
        np.vstack(rows).astype(np.float32),
        np.asarray(labels, dtype=np.float32),
        np.asarray(group_ids, dtype=np.int64),
        np.asarray(pairs, dtype=np.int32),
        np.asarray(pairs_weight, dtype=np.float32),
        stats,
    )


def make_group_splits(groups, n_splits=5):
    splitter = GroupKFold(n_splits=n_splits)
    return list(splitter.split(X_train_raw, y, groups=groups))


splits = make_group_splits(groups_center, n_splits=5)
quick_tr_idx, quick_va_idx = splits[0]
quick_pp = FoldPreprocessor().fit(X_train_raw.iloc[quick_tr_idx])
quick_X_tr_pp = quick_pp.transform(X_train_raw.iloc[quick_tr_idx])
_, _, _, _, _, quick_pair_stats = build_pairwise_query_data(
    quick_X_tr_pp,
    y_full[quick_tr_idx],
    fold_seed=1,
    max_comparators=MAX_COMPARATORS_PER_ANCHOR,
    materialize=True,
)
quick_pair_stats.update(
    {
        "fold": 1,
        "train_rows": int(len(quick_tr_idx)),
        "valid_rows": int(len(quick_va_idx)),
        "preprocessed_features": int(quick_X_tr_pp.shape[1]),
        "pair_construction_scope": "training_fold_only",
        "censoring_km_scope": "training_fold_only",
    }
)
quick_pair_query_check = pd.DataFrame([quick_pair_stats])
quick_pair_query_check.to_csv(OUTPUT_DIR / "exp01_quick_pair_query_check.csv", index=False)
display(quick_pair_query_check)

del quick_pp, quick_X_tr_pp
gc.collect()

if EXP01_QUICK_CHECK_ONLY:
    no_submission_summary = pd.DataFrame(
        [
            {
                "script": "leukemia_survival_exp01_catboost_ipcw_pairrank.py",
                "mode": "quick_check_only",
                "submission_files_generated": 0,
                "catboost_available": bool(HAS_CATBOOST),
                "catboost_preflight_passed": bool(CATBOOST_PREFLIGHT_PASSED),
                "v6_train_shape": str(tuple(X_train_raw.shape)),
                "v6_test_shape": str(tuple(X_test_raw.shape)),
            }
        ]
    )
    no_submission_summary.to_csv(OUTPUT_DIR / "exp01_no_submission_summary.csv", index=False)
    assert not list(OUTPUT_DIR.glob("submission*.csv")), "Quick check should not generate submission CSVs."
    print("EXP01_QUICK_CHECK_ONLY=1: skipping full EXP01 CatBoost CV.")
    print("No submission files generated.")
    sys.exit(0)


# %% [markdown]
# # Full EXP01 diagnostic run

# %%
def common_catboost_params(config):
    return {
        "loss_function": config["loss_function"],
        "iterations": int(config["iterations"]),
        "depth": int(config["depth"]),
        "learning_rate": float(config["learning_rate"]),
        "l2_leaf_reg": float(config["l2_leaf_reg"]),
        "random_seed": RANDOM_STATE,
        "thread_count": 1,
        "allow_writing_files": False,
        "verbose": False,
        "task_type": "CPU",
    }


def score_oof_rank(oof_rank_values):
    if not np.isfinite(oof_rank_values).all():
        raise ValueError("OOF rank vector contains non-finite values.")
    return float(concordance_index_ipcw(y_full, y_full, oof_rank_values, tau=TAU)[0])


def run_catboost_candidate(config):
    if not HAS_CATBOOST:
        raise RuntimeError("CatBoost is not installed.")
    if not CATBOOST_PREFLIGHT_PASSED:
        raise RuntimeError("CatBoost preflight failed.")

    name = config["name"]
    start = time.time()
    oof_pred = np.full(len(X_train_raw), np.nan, dtype=float)
    fold_test_ranks = []
    fold_rows = []
    query_rows = []

    for fold, (tr_idx, va_idx) in enumerate(splits, start=1):
        try:
            pp = FoldPreprocessor().fit(X_train_raw.iloc[tr_idx])
            X_tr_pp = pp.transform(X_train_raw.iloc[tr_idx])
            X_va_pp = pp.transform(X_train_raw.iloc[va_idx])
            X_test_pp = pp.transform(X_test_raw)

            X_pair, label_pair, group_id, pairs, pairs_weight, stats = build_pairwise_query_data(
                X_tr_pp,
                y_full[tr_idx],
                fold_seed=fold,
                max_comparators=MAX_COMPARATORS_PER_ANCHOR,
                materialize=True,
            )

            pool = Pool(
                data=X_pair,
                label=label_pair,
                group_id=group_id,
                pairs=pairs,
                pairs_weight=pairs_weight,
            )
            model = CatBoostRanker(**common_catboost_params(config))
            model.fit(pool)

            pred_va = np.asarray(model.predict(X_va_pp), dtype=float).reshape(-1)
            pred_test = np.asarray(model.predict(X_test_pp), dtype=float).reshape(-1)
            if not np.isfinite(pred_va).all() or not np.isfinite(pred_test).all():
                raise ValueError("non-finite CatBoost predictions")

            oof_pred[va_idx] = pred_va
            fold_test_ranks.append(rank01(pred_test))
            fold_score = ipcw_score(y_full[tr_idx], y_full[va_idx], pred_va)

            fold_rows.append(
                {
                    "candidate": name,
                    "fold": fold,
                    "status": "success",
                    "ipcw_cindex": fold_score,
                    "valid_rows": int(len(va_idx)),
                }
            )
            stats.update({"candidate": name, "fold": fold, "status": "success"})
            query_rows.append(stats)
            print(f"{name} fold {fold}: IPCW={fold_score:.6f}, pairs={stats['pairs_after_cap']}")
        except Exception as exc:
            fold_rows.append(
                {
                    "candidate": name,
                    "fold": fold,
                    "status": "failed",
                    "ipcw_cindex": np.nan,
                    "valid_rows": int(len(va_idx)),
                    "message": repr(exc),
                }
            )
            query_rows.append({"candidate": name, "fold": fold, "status": "failed", "message": repr(exc)})
            print(f"Skipping {name} fold {fold}: {repr(exc)}")
            continue

    complete = np.isfinite(oof_pred).all()
    if not complete:
        raise RuntimeError(f"{name} did not produce complete OOF predictions.")

    oof_rank = rank01(oof_pred)
    test_rank = np.mean(fold_test_ranks, axis=0)
    score = score_oof_rank(oof_rank)
    elapsed_sec = time.time() - start

    score_row = {
        "candidate": name,
        "family": config["family"],
        "loss_function": config["loss_function"],
        "status": "success",
        "oof_ipcw": score,
        "elapsed_sec": elapsed_sec,
    }
    return score_row, fold_rows, query_rows, oof_pred, oof_rank, test_rank


score_rows = []
fold_rows_all = []
query_rows_all = []
oof_outputs = {}

if HAS_CATBOOST and CATBOOST_PREFLIGHT_PASSED:
    for config in EXP01_CATBOOST_CONFIGS:
        try:
            score_row, fold_rows, query_rows, oof_pred, oof_rank, test_rank = run_catboost_candidate(config)
            score_rows.append(score_row)
            fold_rows_all.extend(fold_rows)
            query_rows_all.extend(query_rows)
            name = config["name"]
            oof_outputs[f"oof_pred__{name}"] = oof_pred
            oof_outputs[f"oof_rank__{name}"] = oof_rank
            oof_outputs[f"test_rank__{name}"] = test_rank
        except Exception as exc:
            score_rows.append(
                {
                    "candidate": config["name"],
                    "family": config["family"],
                    "loss_function": config["loss_function"],
                    "status": "failed",
                    "oof_ipcw": np.nan,
                    "message": repr(exc),
                }
            )
            print(f"Candidate failed: {config['name']}: {repr(exc)}")
else:
    for config in EXP01_CATBOOST_CONFIGS:
        score_rows.append(
            {
                "candidate": config["name"],
                "family": config["family"],
                "loss_function": config["loss_function"],
                "status": "skipped_missing_or_failed_dependency",
                "oof_ipcw": np.nan,
                "message": "CatBoost missing or preflight failed.",
            }
        )

score_df = pd.DataFrame(score_rows)
fold_df = pd.DataFrame(fold_rows_all)
query_df = pd.DataFrame(query_rows_all)
score_df.to_csv(OUTPUT_DIR / "exp01_candidate_scores.csv", index=False)
fold_df.to_csv(OUTPUT_DIR / "exp01_foldwise_scores.csv", index=False)
query_df.to_csv(OUTPUT_DIR / "exp01_query_stats.csv", index=False)

successful_names = score_df.loc[score_df["status"] == "success", "candidate"].tolist()
if successful_names:
    rank_df = pd.DataFrame({name: oof_outputs[f"oof_rank__{name}"] for name in successful_names})
    rank_df.corr(method="spearman").to_csv(OUTPUT_DIR / "exp01_rank_correlation_matrix.csv")

    blend_rows = []
    reference_rank = None
    reference_message = ""
    try:
        v8 = np.load(Path("qrt_outputs_v8") / "v8cd_oof_predictions.npz")
        exp02 = np.load(Path("qrt_outputs_exp02") / "exp02_oof_test_rank_vectors.npz")
        v8e_rank = 0.42857142857142855 * rank01(v8["extra"]) + 0.5714285714285714 * rank01(v8["xgb_cox_d3_lr02"])
        reference_rank = 0.90 * rank01(v8e_rank) + 0.10 * rank01(exp02["text_only_coxnet__iscn_token_tfidf"])
        reference_score = score_oof_rank(reference_rank)
        reference_message = "current_v8e_text10_reference_reconstructed"
    except Exception as exc:
        reference_score = np.nan
        reference_message = f"reference_unavailable: {repr(exc)}"

    for name in successful_names:
        candidate_rank = oof_outputs[f"oof_rank__{name}"]
        candidate_score = score_oof_rank(candidate_rank)
        blend_rows.append(
            {
                "blend": name,
                "catboost_weight": 1.0,
                "oof_ipcw": candidate_score,
                "reference_oof_ipcw": reference_score,
                "reference_message": reference_message,
            }
        )
        if reference_rank is not None:
            for weight in [0.025, 0.05, 0.075, 0.10, 0.15]:
                blend_rank = (1.0 - weight) * rank01(reference_rank) + weight * rank01(candidate_rank)
                blend_rows.append(
                    {
                        "blend": f"current_ref_plus_{name}",
                        "catboost_weight": weight,
                        "oof_ipcw": score_oof_rank(blend_rank),
                        "reference_oof_ipcw": reference_score,
                        "reference_message": reference_message,
                    }
                )
    pd.DataFrame(blend_rows).to_csv(OUTPUT_DIR / "exp01_blend_scores.csv", index=False)
    np.savez_compressed(OUTPUT_DIR / "exp01_oof_test_rank_vectors.npz", **oof_outputs)
else:
    pd.DataFrame(
        [
            {
                "blend": "none",
                "status": "no_successful_catboost_candidates",
            }
        ]
    ).to_csv(OUTPUT_DIR / "exp01_blend_scores.csv", index=False)

no_submission_summary = pd.DataFrame(
    [
        {
            "script": "leukemia_survival_exp01_catboost_ipcw_pairrank.py",
            "mode": "full_diagnostic",
            "submission_files_generated": 0,
            "successful_candidates": int(len(successful_names)),
        }
    ]
)
no_submission_summary.to_csv(OUTPUT_DIR / "exp01_no_submission_summary.csv", index=False)
assert not list(OUTPUT_DIR.glob("submission*.csv")), "EXP01 diagnostics should not generate submission CSVs."

print("\nEXP01 candidate scores:")
display(score_df)
print("No submission files generated.")
